### PR TITLE
Delete ghcr-publish.yml

### PR DESCRIPTION
**Pull request by TohoEnjoyer2000**
it doesn't work like that

### CODE REVIEW

**Comment by AmirulAndalib** [comment]
> it doesn't work like that

what do you mean?

**Comment by AmirulAndalib** [comment]
> it doesn't work like that

https://github.com/AmirulAndalib/yt-dlp-web-ui/actions/runs/3950047002/jobs/6762057290

**Comment by TohoEnjoyer2000** [comment]
you can't just take a repo change the author name with yours and republish the container

**Comment by AmirulAndalib** [comment]
> you can't just take a repo change the author name with yours and republish the container

stop being a foolish person checm the license first then talk 
https://github.com/marcopeocchi/yt-dlp-web-ui/blob/master/LICENSE.md

**Comment by marcopeocchi** [comment]
conditions: Disclose source

**Pull request closed without merging**
